IF OBJECT_ID(N'Movies.CrewMember') IS NULL
BEGIN
CREATE TABLE [Movies].[CrewMember]
(
	[CrewMemberID] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	PersonTypeID TINYINT NOT NULL,
	FirstName NVARCHAR(15) NOT NULL,
	LastName NVARCHAR(15) NOT NULL,

	FOREIGN KEY(PersonTypeID) REFERENCES Movies.PersonType(PersonTypeID)
)
END;